eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
      

        
spring:
  zipkin:
    baseUrl: http://127.0.0.1:9411
    
    
okta:
  oauth2:
    issuer: https://dev-22116469.okta.com/oauth2/default
    audience: api://default
